AzureSentinel:
  Workspaces:
    Default:
      ResourceGroup: production_resource_group
      SubscriptionId: 37b41c49-f29e-44fa-90f4-937060c237c9
      TenantId: a4d0c603-9c7f-4293-b89c-a08c1a8eb571
      WorkspaceId: a97557b5-b341-450d-ac71-cdd5658a7e03
      WorkspaceName: log-analytics-workspace-wedc
      user_alias: gcadmin@corp.wedc.org
DataProviders:
  LocalData:
    data_paths: []
KeyVault:
  Authority: global
  AzureRegion: centralus
  ResourceGroup: Production_Resource_Group
  SubscriptionId: 37b41c49-f29e-44fa-90f4-937060c237c9
  TenantId: a4d0c603-9c7f-4293-b89c-a08c1a8eb571
  UseKeyring: true
  VaultName: key-vault-prod-wedc
OtherProviders:
  GeoIPLite:
    Args:
      AuthKey: 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
      DBFolder: ~/.msticpy
    Provider: GeoLiteLookup
  IPStack:
    Args:
      AuthKey: 0c2d991997eaf00ca1496f7f87b4b398
    Provider: IPStackLookup
TIProviders:
  AzureSentinel:
    Args:
      TenantID: a4d0c603-9c7f-4293-b89c-a08c1a8eb571
      WorkspaceID: a97557b5-b341-450d-ac71-cdd5658a7e03
    Primary: true
    Provider: AzSTI
  VirusTotal:
    Args:
      AuthKey: 0a8efd3bcc46ddab579ef5f1d1969913168eb2a822096060873c16a8bee66027
      UseVT3PrivateAPI: false
    Primary: true
    Provider: VirusTotal
  XForce:
    Args:
      ApiID: 49fc7057-5fdb-466f-a3ea-3ac6d2cbbf72
      AuthKey: eebcf0e8-8c66-48e3-ba8f-0f50d25299f5
    Primary: false
    Provider: XForce
UserDefaults:
  LoadComponents: {}
  QueryProviders: {}
